name: zcash-params

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      # parameter download code
      - 'zebra-consensus/src/primitives/groth16/params.rs'
      - 'zebra-consensus/src/chain.rs'
      - 'zebrad/src/commands/start.rs'
      # workflow definitions
      - 'docker/zcash-params/Dockerfile'
      - '.github/workflows/zcash-params.yml'
      - '.github/workflows/docker-image-build.yml'

jobs:
  build:
    # TODO: before merging change uses to ZcashFoundation/zebra/.github/workflows/docker-image-build.yml@main
    uses: ./.github/workflows/docker-image-build.yml
    with:
      dockerfile_path: ./docker/zcash-params/Dockerfile
      dockerfile_target: builder
      image_name: zcash-params
      network: Mainnet
      checkpoint_sync: true
      rust_backtrace: full
      rust_lib_backtrace: full
      colorbt_show_hidden: '1'
      zebra_skip_network_tests: '1'
      rust_log: debug
